

coils = {
    0: {"payload_on": True,
        "payload_off": False},
    1: {"payload_on": True,
        "payload_off": False},
    2: {"payload_on": True,
        "payload_off": False},
    3: None,
    4: None,
    5: {"payload_on": True,
        "payload_off": False},
    6: {"payload_on": True,
        "payload_off": False},
    7: {"payload_on": True,
        "payload_off": False},
    8: {"payload_on": True,
        "payload_off": False},
    9: {"payload_on": True,
        "payload_off": False},
    10: {"payload_on": True,
         "payload_off": False},
    11: {"payload_on": True,
         "payload_off": False},
    12: {"payload_on": True,
         "payload_off": False},
    13: {"payload_on": True,
         "payload_off": False},
    14: {"payload_on": True,
         "payload_off": False},
    15: {"payload_on": True,
         "payload_off": False},
    16: {"payload_on": True,
         "payload_off": False},
    17: {"payload_on": True,
         "payload_off": False},
    18: {"payload_on": True,
         "payload_off": False},
    19: None,
    20: None,
    21: None,
    22: {"payload_on": True,
         "payload_off": False},
    23: {"payload_on": True,
         "payload_off": False},
    24: {"payload_on": True,
         "payload_off": False}
}
