

holding_registers = {
    0: "mdi:fan-auto",
    1: "mdi:fan-speed-3",
    2: "mdi:fan-speed-1",
    3: "mdi:fan",
    4: "mdi:fan",
    5: "mdi:fan",
    6: "mdi:fan",
    7: "mdi:fan",
    8: "mdi:fan",
    9: "mdi:fan",
    10: "mdi:fan",
    11: "mdi:fan",
    12: "mdi:fan",
    13: "mdi:fan",
    14: "mdi:fan",
    15: "mdi:fan",
    16: "mdi:fan",
    17: "mdi:fan",
    18: "mdi:fan",
    19: "mdi:fan",
    20: "mdi:fan",
    21: "mdi:fan",
    22: "mdi:fan",
    23: "mdi:fan",
    24: "mdi:fan",
    25: "mdi:fan",
    26: "mdi:fan",
    27: "mdi:fan",
    28: "mdi:fan",
    29: "mdi:fan",
    30: "mdi:fan",
    31: "mdi:fan",
    32: "mdi:fan",
    33: "mdi:fan",
    34: "mdi:fan",
    35: "mdi:fan",
    36: "mdi:fan",
    37: "mdi:gauge",
    38: "mdi:gauge",
    39: "mdi:gauge",
    40: "mdi:gauge",
    41: "mdi:gauge",
    42: "mdi:gauge",
    43: "mdi:view-list",
    44: "mdi:thermometer",
    74: "mdi:view-list",
    75: "mdi:gauge"
}

