

input_registers = {
    0: "mdi:thermometer",
    1: "mdi:thermometer",
    2: "mdi:thermometer",
    3: "mdi:thermometer",
    4: "mdi:thermometer",
    5: "mdi:thermometer",
    8: "mdi:thermometer",
    9: "mdi:flash-triangle",
    10: "mdi:water-percent",
    11: "mdi:water-percent",
    12: "mdi:molecule-co2",
    13: "mdi:molecule-co2",
    14: "mdi:molecule-co2",
    15: "mdi:molecule-co2",
    16: "mdi:molecule-co2",
    17: "mdi:molecule-co2",
    18: "mdi:percent",
    19: "mdi:gauge",
    20: "mdi:gauge",
    21: "mdi:gauge",
    22: "mdi:gauge",
    23: "mdi:gauge",
    24: "mdi:gauge",
    25: "mdi:clock-outline",
    27: "mdi:clock-outline",
    29: "mdi:clock-outline",
    31: "mdi:air-filter",
    32: "mdi:gauge",
    33: "mdi:thermometer",
    34: "mdi-update",
    37: "mdi:power-socket-uk",
    38: "mdi:alarm-light",
    39: "mdi:signal",
    40: "mdi:signal",
    41: "mdi:signal",
    42: "mdi:signal",
    43: "mdi:signal",
    44: "mdi:signal",
    45: "mdi:signal",
    46: "mdi:signal",
    47: "mdi:signal",
    48: "mdi:thermometer",
    49: "mdi:thermometer",
    50: "mdi:thermometer",
}
