

alarms = {
    0: "Alarm! Supply fan malfunction",
    1: "Alarm! Extract fan malfunction. Determined depending on a specific configuration",
    2: "Alarm! No outdoor air temperature sensor detected",
    3: "Alarm! Short circuit of the outdoor air temperature sensor",
    4: "Alarm! No supply air temperature sensor detected",
    5: "Alarm! Short circuit of the supply air temperature sensor",
    6: "Alarm! No sensor of the extract air temperature upstream of the heat exchanger detected",
    7: "Alarm! Short circuit of the extract air temperature sensor",
    8: "Alarm! No sensor of the exhaust air temperature downstream of the heat exchanger detected",
    9: "Alarm! Short circuit of the exhaust air temperature sensor",
    10: "Alarm! Preheater protective thermostat activated",
    11: "Alarm! Main heater protective thermostat activated",
    12: "Alarm! Preheating cannot provide heat exchanger freezing protection",
    13: "Warning! Main humidity sensor not detected",
    14: "Warning! Main CO₂ sensor not detected",
    15: "Warning! Main PM2.5 sensor not detected",
    16: "Warning! Main VOC sensor not detected",
    17: "Warning! External humidity sensor not detected",
    18: "Warning! External CO₂ sensor not detected",
    19: "Warning! External PM2.5 sensor not detected",
    20: "Warning! External VOC sensor not detected",
    21: "Warning! Indoor air temperature not detected",
    22: "Warning! Heat exchanger freezing danger",
    23: "Warning! The battery is low",
    24: "Warning! Replace the supply air filter",
    25: "Alarm! Fire alarm activated",
    26: "Alarm! Low supply air temperature",
    27: "Alarm! Return water temperature sensor not detected",
    28: "Alarm! Short circuit of the return water temperature sensor",
    29: "Warning! Replace the extract air filter",
    30: "Alarm! No water pressure detected",
    31: "Alarm! No water flow detected",
    32: "Alarm! Low return water temperature",
    33: "Alarm! Supply fan cannot provide heat exchanger freezing protection",
    34: "Alarm! Bypass cannot provide heat exchanger freezing protection",
    35: "Warning! Freeze protection disabled. This may cause heat exchanger freezing",
    36: "Warning! The main heater is operated in the manual mode",
    37: "Warning! The cooler is operated in the manual mode",
    38: "Warning! The bypass is operated in the manual mode",
    39: "Warning! The rotary heat exchanger is operated in manual mode",
    40: "Warning! The filter timer countdown is completed. Please, replace the filter",
    41: "Warning! Incorrect operation of the rotary heat exchanger",
    42: "Warning! Preheater is operated in the manual mode",
    43: "Alarm! Return water temperature failed to reach setpoint in due time before AHU start"
}
