

holding_registers = {
    0: "Ventilation mode",
    1: "Maximum permissible speed number",
    2: "Speed number",
    3: "Minimum possible fan speed",
    4: "Maximum possible fan speed",
    5: "Supply fan speed in Standby mode",
    6: "Extract fan speed in Standby mode",
    7: "Supply fan speed in Speed 1 mode",
    8: "Extract fan speed in Speed 1 mode",
    9: "Supply fan speed in Speed 2 mode",
    10: "Extract fan speed in Speed 2 mode",
    11: "Supply fan speed in Speed 3 mode",
    12: "Extract fan speed in Speed 3 mode",
    13: "Supply fan speed in Speed 4 mode",
    14: "Extract fan speed in Speed 4 mode",
    15: "Supply fan speed in Speed 5 mode",
    16: "Extract fan speed in Speed 5 mode",
    17: "Fan speed in manual speed setting mode",
    18: "Fan speed while blowing electric heaters",
    19: "Supply fan speed in Boost mode",
    20: "Extract fan speed in Boost mode",
    21: "Supply fan speed in Fireplace mode",
    22: "Extract fan speed in Fireplace mode",
    23: "Minimum possible air flow of the unit",
    24: "Maximum possible air flow of the unit",
    25: "Supply air flow in Standby mode",
    26: "Extract air flow in Standby mode",
    37: "Minimum possible pressure in the air duct ",
    38: "Maximum possible pressure in the air duct",
    39: "Pressure in the supply air duct in Standby mode",
    40: "Pressure in the exhaust air duct in Standby mode",
    41: "Pressure in the supply air duct in Speed 1 mode",
    42: "Pressure in the exhaust air duct in Speed 1 mode",
    43: "Unit operation mode. 0 - ventilation only 1 - heating, 2 - cooling, 3 - auto",
    44: "Room temperature setpoint in normal mode"
}

