

input_registers = {
    0: "Current temperature of the selected sensor",
    1: "Current temperature of the main outdoor air sensor before preheating",
    2: "Current temperature of the main supply air temperature sensor",
    3: "Current extract air temperature at the unit inlet",
    4: "Current exhaust air temperature at the unit outlet",
    5: "Current temperature of the outdoor air temperature sensor",
    8: "Return heat medium temperature",
    9: "Current battery voltage for RTC",
    10: "Current humidity of the main sensor",
    11: "Current humidity of the outdoor sensor",
    12: "Current CO2 level of the main sensor",
    13: "Current CO2 level of the external sensor",
    14: "Current PM2.5 level of the main sensor",
    15: "Current PM2.5 level of the external sensor",
    16: "Current VOC level of the main sensor",
    17: "Current VOC level of the external sensor",
    18: "Current value of the 0-10 V sensor",
    19: "Current supply air flow",
    20: "Current exhaust air flow",
    21: "Current pressure in the supply air duct",
    22: "Current pressure in the exhaust air duct",
    23: "Supply fan speed",
    24: "Extract fan speed",
    25: "Current countdown time of the main timer",
    27: "Countdown time of the filter replacement timer",
    29: "Motor hours",
    31: "Filter condition",
    32: "Current speed in Weekly schedule mode",
    33: "Current temperature setpoint in Weekly schedule mode",
    34: "Firmware version",
    37: "Device type (controller)",
    38: "Alarm/warning indicator",
    39: "Controls signal from the PID humidity controller",
    40: "Controls signal from the PID CO2 level controller",
    41: "Controls signal from the PID PM2.5 level controlle",
    42: "Controls signal from the PID VOC level controller",
    43: "Controls signal from the PID preheating controller",
    44: "Controls signal from the PID reheating controller",
    45: "Controls signal from the PID bypass/rotary heat exchanger controller",
    46: "Controls signal from the PID condenser unit controller",
    47: "Controls signal from the PID return heat medium controller",
    48: "Temperature setpoint in the supply air duct",
    49: "Return heat medium temperature setpoint during winter in Standby mode",
    50: "Return heat medium temperature setpoint in winter before the air handling unit start-up"
}
