

holding_registers = {
    0: "HR_VENTILATION_MODE",
    1: "HR_MaxSPEED_MODE",
    2: "HR_SPEED_MODE",
    3: "HR_MinSPEED",
    4: "HR_MaxSPEED",
    5: "HR_SuSPEED0",
    6: "HR_ExSPEED0",
    7: "HR_SuSPEED1",
    8: "HR_ExSPEED1",
    9: "HR_SuSPEED2",
    10: "HR_ExSPEED2",
    11: "HR_SuSPEED3",
    12: "HR_ExSPEED3",
    13: "HR_SuSPEED4",
    14: "HR_ExSPEED4",
    15: "HR_SuSPEED5",
    16: "HR_ExSPEED5",
    17: "HR_ManualSPEED",
    18: "HR_BlowingSPEED",
    19: "HR_Boost_SuSPEED",
    20: "HR_Boost_ExSPEED",
    21: "HR_FPLC_SuSPEED",
    22: "HR_FPLC_ExSPEED",
    23: "HR_MinAirFLOW",
    24: "HR_MaxAirFLOW",
    25: "HR_SuSPEED0_FLOW",
    26: "HR_ExSPEED0_FLOW",
    37: "HR_MinAirPRESS",
    38: "HR_MaxAirPRESS",
    39: "HR_SuSPEED0_PRESS",
    40: "HR_ExSPEED0_PRESS",
    41: "HR_SuSPEED1_PRESS",
    42: "HR_ExSPEED1_PRESS",
    43: "HR_OPERATION_MODE",
    44: "HR_SetTEMP"
}

