

input_registers = {
    0: "IR_CurSelTEMP",
    1: "IR_CurTEMP_SuAirIn",
    2: "IR_CurTEMP_SuAirOut",
    3: "IR_CurTEMP_ExAirIn",
    4: "IR_CurTEMP_ExAirOut",
    5: "IR_CurTEMP_Ext",
    8: "IR_CurTEMP_Water",
    9: "IR_CurVBAT",
    10: "IR_CurRH_Int",
    11: "IR_CurRH_Ext",
    12: "IR_CurCO2_Int",
    13: "IR_CurCO2_Ext",
    14: "IR_CurPM2_5_Int",
    15: "IR_CurPM2_5_Ext",
    16: "IR_CurVOC_Int",
    17: "IR_CurVOC_Ext",
    18: "IR_Cur10V_SENSOR",
    19: "IR_CurSuAirFLOW",
    20: "IR_CurExAirFLOW",
    21: "IR_CurSuPRESS",
    22: "IR_CurExPRESS",
    23: "IR_SuRPM",
    24: "IR_ExRPM",
    25: "IR_CurTIMER_TIME",
    27: "IR_CurFILTER_TIMER",
    29: "IR_TotalWorkingTime",
    31: "IR_StateFILTER",
    32: "IR_CurWeekSpeed",
    33: "IR_CurWeekSetTemp",
    34: "IR_VerMAIN_FMW",
    37: "IR_DeviceTYPE",
    38: "IR_ALARM",
    39: "IR_RH_U",
    40: "IR_CO2_U",
    41: "IR_PM2_5_U",
    42: "IR_VOC_U",
    43: "IR_PreHeater_U",
    44: "IR_MainHeater_U",
    45: "IR_BPS_ROTOR_U",
    46: "IR_KKB_U",
    47: "IR_ReturnWater_U",
    48: "IR_SuAirOutSetTemp",
    49: "IR_WaterStandbySetTemp",
    50: "IR_WaterStartSetTemp"
}
